### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by i-am-annewang** [i-am-annewang/cake#1]
# Cake

## 模块
- [ ] 商品模块
- [ ] 购物车模块
- [ ] 订单模块
- [ ] 用户模块
- [ ] 管理员模块

## Todo
- [x] Restful API
- [x] React,  [express-react-views](https://github.com/reactjs/express-react-views) as express engine
- [ ] Typescript
- [x] express.js
- [x] postgreSQL, 和mysql一样是关系型数据库，开源，而且可以以字符串形式存储一个对象
- [x] [node-postgres](https://node-postgres.com) ORM

## Restful API
- [x] home, /
- [x] category, /category/dessert
- [x] product, /product/1
- [x] cart, /cart/1
- [x] order, /order/1
- [x] user, /user/1
- [ ] admin, /admin

## React
- [ ] next.js: server(node.js), pages
- [ ] storybook: atoms, molecules, containers

## UI设计
-  商品
   - [ ] 商品列表页
   - [ ] 商品详细页
- 购物车
  - [ ] 购物车页面
- 订单
  - [ ] 订单成功
  - [ ] 订单失败
- 用户
  - [ ] 登录页
  - [ ] 注册页
  - [ ] 个人信息页
- 管理员
  - [ ] 创建商品页
  - [ ] 编辑商品页

## 后端postgreSQL
- [x] datebase: cake
  - [x] table:
    - [ ] categories
    - [ ] products 外键categoryId
    - [ ] carts 外键 productId, userId
    - [ ] orders 外键userId
    - [ ] users
    + 依赖user
      - [ ] address
      - [ ] recommand
      - [ ] read_history
      - [ ] order_history

## 辅助功能
- [x] grunt/webpack, refer: [Nodejs 配置自动重启与页面刷新](http://albertchen.top/2015/11/03/Nodejs%E9%85%8D%E7%BD%AE%E8%87%AA%E5%8A%A8%E9%87%8D%E5%90%AF%E4%B8%8E%E9%A1%B5%E9%9D%A2%E5%88%B7%E6%96%B0/)

## 项目管理
- [x] git管理项目
- [x] github托管项目
